<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DotnetApiTemplate.Cli.UnitTests</RootNamespace>
    <AssemblyName>DotnetApiTemplate.Cli.UnitTests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CA1707;CA2007;CA1861;CA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetApiTemplate.Cli\DotnetApiTemplate.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
