<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CleanArchTemplate.Api.IntegrationTests</RootNamespace>
    <AssemblyName>CleanArchTemplate.Api.IntegrationTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CleanArchTemplate.Api\CleanArchTemplate.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Testcontainers.Redpanda" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

</Project>
